security:
     encoders:
         FOS\UserBundle\Model\UserInterface: bcrypt

     providers:
         fos_userbundle:
             id: fos_user.user_provider.username

     firewalls:
         dev:
             pattern: ^/(_(profiler|wdt)|css|images|js)/
             security: false
         main:
             pattern: ^/
             anonymous: true
             form_login:
                 provider: fos_userbundle
                 csrf_token_generator: security.csrf.token_manager
                 use_referer: true
             logout:
                 path: /logout
                 target: /login

     access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
